-- MySQL Script generated by MySQL Workbench
-- Fri Nov 21 17:04:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trabalhoberg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trabalhoberg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalhoberg` DEFAULT CHARACTER SET utf8 ;
USE `trabalhoberg` ;

-- -----------------------------------------------------
-- Table `trabalhoberg`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhoberg`.`autores` (
  `id_autores` INT NOT NULL AUTO_INCREMENT,
  `nome_autor` VARCHAR(100) NOT NULL,
  `nacionalidade` VARCHAR(50) NOT NULL,
  `data_cadastro` DATE NOT NULL,
  PRIMARY KEY (`id_autores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhoberg`.`livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhoberg`.`livros` (
  `id_livros` INT NOT NULL AUTO_INCREMENT,
  `titulos` VARCHAR(255) NOT NULL,
  `ano_publicado` YEAR NULL,
  `autores_id_autores` INT NOT NULL,
  PRIMARY KEY (`id_livros`, `autores_id_autores`),
  INDEX `fk_livros_autores_idx` (`autores_id_autores` ASC) ,
  CONSTRAINT `fk_livros_autores`
    FOREIGN KEY (`autores_id_autores`)
    REFERENCES `trabalhoberg`.`autores` (`id_autores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
